## **Tensors**

* Similar to arrays and matrix
* Used as model parameters, encoders to input & output
* Tensors can also run on GPUs 
* By default, tensors are created in CPU

In [1]:
import torch
import numpy as np

### **Initializing a Tensor**

#### **i) Directly from data**

In [2]:
data = [[1, 2],[3, 4]]
x_data = torch.tensor(data)
print(x_data)

tensor([[1, 2],
        [3, 4]])


#### **ii) From a NumPy array**

In [3]:
np_array = np.array(data)
x_np = torch.from_numpy(np_array)
print(x_np)

tensor([[1, 2],
        [3, 4]], dtype=torch.int32)


#### **iii) From another tensor**

The new tensor have same property as old tensor, but we can overwrite its properters as per our need.

In [4]:
x_ones = torch.ones_like(x_data) # retains the properties of x_data
print(f"Ones Tensor: \n {x_ones} \n")

x_rand = torch.rand_like(x_data, dtype=torch.float) # overrides the datatype of x_data
print(f"Random Tensor: \n {x_rand} \n")

Ones Tensor: 
 tensor([[1, 1],
        [1, 1]]) 

Random Tensor: 
 tensor([[0.8287, 0.4023],
        [0.8815, 0.7851]]) 



#### **iv) With random or constant values**

`shape` : Tuple of tensor dimensions

In [5]:
shape = (2,3,)
rand_tensor = torch.rand(shape)
ones_tensor = torch.ones(shape)
zeros_tensor = torch.zeros(shape)

print(f"Random Tensor: \n {rand_tensor} \n")
print(f"Ones Tensor: \n {ones_tensor} \n")
print(f"Zeros Tensor: \n {zeros_tensor}")

Random Tensor: 
 tensor([[0.1383, 0.4599, 0.5362],
        [0.8820, 0.4580, 0.6098]]) 

Ones Tensor: 
 tensor([[1., 1., 1.],
        [1., 1., 1.]]) 

Zeros Tensor: 
 tensor([[0., 0., 0.],
        [0., 0., 0.]])


In [6]:
k = torch.rand(2, 3)            # Initialize with random number ---- uniform distribution
l = torch.randn(2, 3)           # With normal distribution (SD=1, mean=0)
m = torch.randperm(4)           # Size 4. Random permutation of integers from 0 to 3

print("Tensor with uniform Distribution \n", k)
print("Tensor with Normal Distribution \n", l)
print("Tensor with Random Permutation \n", m)

Tensor with uniform Distribution 
 tensor([[0.8622, 0.8769, 0.9234],
        [0.0898, 0.0331, 0.6387]])
Tensor with Normal Distribution 
 tensor([[ 0.6303,  1.7385, -0.2545],
        [-0.2860, -0.5228,  0.5595]])
Tensor with Random Permutation 
 tensor([3, 0, 1, 2])


### **Attributes of a Tensor**

* Shape
* datatype
* device in which they are stored

In [7]:
tensor = torch.rand(3,4)

print("Shape of tensor: ", tensor.shape)
print("Datatype of tensor: ", tensor.dtype)
print("Device tensor is stored on: ", tensor.device)

Shape of tensor:  torch.Size([3, 4])
Datatype of tensor:  torch.float32
Device tensor is stored on:  cpu


### **Operations on Tensors**

Example: Arithmetic, Linear Algebra, Matrix Manipulation (transposing, indexing, slicing), Sampling etc.

To use tensor in GPU use `.to` method.

In [8]:
# to use tensor in gpu
if torch.cuda.is_available():
    tensor = tensor.to('cuda')

In [9]:
print(tensor.device)            # doesn't have cuda, nvidia gpu

cpu


#### **To verify whether it is tensor or not**

In [10]:
torch.is_tensor(tensor)

True

#### i) **Standard numpy-like indexing and slicing**

In [11]:
tensor = torch.ones(4, 4)
print('First row: ', tensor[0])
print('First column: ', tensor[:, 0])
print('Last column:', tensor[:, -1])
tensor[:,1] = 0
print(tensor)

First row:  tensor([1., 1., 1., 1.])
First column:  tensor([1., 1., 1., 1.])
Last column: tensor([1., 1., 1., 1.])
tensor([[1., 0., 1., 1.],
        [1., 0., 1., 1.],
        [1., 0., 1., 1.],
        [1., 0., 1., 1.]])


#### **ii) Joining tensors**

`torch.cat` : To concatenate along **given dimension**

In [12]:
t1 = torch.cat([tensor, tensor, tensor], dim=1)
print(t1)

tensor([[1., 0., 1., 1., 1., 0., 1., 1., 1., 0., 1., 1.],
        [1., 0., 1., 1., 1., 0., 1., 1., 1., 0., 1., 1.],
        [1., 0., 1., 1., 1., 0., 1., 1., 1., 0., 1., 1.],
        [1., 0., 1., 1., 1., 0., 1., 1., 1., 0., 1., 1.]])


In [13]:
t2 = torch.cat([tensor, tensor, tensor], dim=0)
print(t2)

tensor([[1., 0., 1., 1.],
        [1., 0., 1., 1.],
        [1., 0., 1., 1.],
        [1., 0., 1., 1.],
        [1., 0., 1., 1.],
        [1., 0., 1., 1.],
        [1., 0., 1., 1.],
        [1., 0., 1., 1.],
        [1., 0., 1., 1.],
        [1., 0., 1., 1.],
        [1., 0., 1., 1.],
        [1., 0., 1., 1.]])


`torch.stack` : To concatenate along new a **new dimention**

**Note:** All tensor need to be of same size.

In [14]:
t3 = torch.stack([tensor, tensor, tensor], dim=1)
print(t3)

tensor([[[1., 0., 1., 1.],
         [1., 0., 1., 1.],
         [1., 0., 1., 1.]],

        [[1., 0., 1., 1.],
         [1., 0., 1., 1.],
         [1., 0., 1., 1.]],

        [[1., 0., 1., 1.],
         [1., 0., 1., 1.],
         [1., 0., 1., 1.]],

        [[1., 0., 1., 1.],
         [1., 0., 1., 1.],
         [1., 0., 1., 1.]]])


#### **iii) Arithmetic operations**

`rand_like()` : Returns a tensor of same size as input filled with random numbers from a uniform distribution on the interval [0, 1)

In [15]:
# for matrix multiplication

print("Tensor \n", tensor)
print("Tensor Transpose \n", tensor.T)

y1 = tensor @ tensor.T
y2 = tensor.matmul(tensor.T)

print("1st Tensor \n", y1)
print("2nd Tensor \n", y2)

y3 = torch.rand_like(tensor)
print("Randomly generated tensor \n", y3)
torch.matmul(tensor, tensor.T, out=y3)

Tensor 
 tensor([[1., 0., 1., 1.],
        [1., 0., 1., 1.],
        [1., 0., 1., 1.],
        [1., 0., 1., 1.]])
Tensor Transpose 
 tensor([[1., 1., 1., 1.],
        [0., 0., 0., 0.],
        [1., 1., 1., 1.],
        [1., 1., 1., 1.]])
1st Tensor 
 tensor([[3., 3., 3., 3.],
        [3., 3., 3., 3.],
        [3., 3., 3., 3.],
        [3., 3., 3., 3.]])
2nd Tensor 
 tensor([[3., 3., 3., 3.],
        [3., 3., 3., 3.],
        [3., 3., 3., 3.],
        [3., 3., 3., 3.]])
Randomly generated tensor 
 tensor([[0.9884, 0.2915, 0.6657, 0.9919],
        [0.5107, 0.3275, 0.7976, 0.0377],
        [0.0861, 0.6280, 0.2084, 0.0401],
        [0.9407, 0.8259, 0.8349, 0.1496]])


tensor([[3., 3., 3., 3.],
        [3., 3., 3., 3.],
        [3., 3., 3., 3.],
        [3., 3., 3., 3.]])

In [16]:
# for element wise product

z1 = tensor * tensor
z2 = tensor.mul(tensor)

z3 = torch.rand_like(tensor)
torch.mul(tensor, tensor, out=z3)

tensor([[1., 0., 1., 1.],
        [1., 0., 1., 1.],
        [1., 0., 1., 1.],
        [1., 0., 1., 1.]])

#### **iv) Single-element tensors**

`item()` : To convert into python numerical value

In [17]:
agg = tensor.sum()
print(agg, type(agg))

agg_item = agg.item()
print(agg_item, type(agg_item))

tensor(12.) <class 'torch.Tensor'>
12.0 <class 'float'>


#### **v) In-place operations**

These store the result into the operand. Denoted by `_`

In [18]:
print(tensor, "\n")

tensor.add_(5)

print(tensor)

tensor([[1., 0., 1., 1.],
        [1., 0., 1., 1.],
        [1., 0., 1., 1.],
        [1., 0., 1., 1.]]) 

tensor([[6., 5., 6., 6.],
        [6., 5., 6., 6.],
        [6., 5., 6., 6.],
        [6., 5., 6., 6.]])


#### **Tensor meta-data**

To find size of tensor and number of elements in tensor.

In [19]:
print("Size of tensor: ", tensor.size())                        
print("Number of elements of tensor: ", torch.numel(tensor)) 

Size of tensor:  torch.Size([4, 4])
Number of elements of tensor:  16


#### **Reshape Tensor**

In [20]:
y = tensor.view(16)                 
z = tensor.view(-1, 2)     
print(y.size())
print(z.size())

torch.Size([16])
torch.Size([8, 2])


### **Bridge with NumPy**

#### **Tensor to NumPy array**

In [21]:
t = torch.ones(5)
print(f"t: {t}")

n = t.numpy()
print(f"n: {n}")

t: tensor([1., 1., 1., 1., 1.])
n: [1. 1. 1. 1. 1.]


A change in the tensor reflects in the NumPy array.

In [22]:
t.add_(1)
print(f"t: {t}")
print(f"n: {n}")

t: tensor([2., 2., 2., 2., 2.])
n: [2. 2. 2. 2. 2.]


#### **NumPy array to Tensor**

In [23]:
n = np.ones(5)
t = torch.from_numpy(n)

print("n: ", n)
print("t: ", t)

n:  [1. 1. 1. 1. 1.]
t:  tensor([1., 1., 1., 1., 1.], dtype=torch.float64)


Changes in the NumPy array reflects in the tensor.

In [24]:
np.add(n, 1, out=n)
print(f"t: {t}")
print(f"n: {n}")

t: tensor([2., 2., 2., 2., 2.], dtype=torch.float64)
n: [2. 2. 2. 2. 2.]
